services:
  api-metro:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_metro_prolog_container
    ports:
      - "8070:8070"
    volumes:
      - .:/app
    # Sobrescribimos el comando por defecto para activar el autorefresh en desarrollo
    command: uvicorn main:app --host 0.0.0.0 --port 8070 --reload
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
